require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_post_install'

platform :ios, '13.0'
project 'PickPlay.xcodeproj'

target 'PickPlay' do
  use_react_native!(
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  use_expo_modules!

end

post_install do |installer|
  react_native_post_install(installer)

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # BoringSSL -G 오류 해결
      if config.build_settings['OTHER_CFLAGS']
        flags = config.build_settings['OTHER_CFLAGS']
        flags = flags.reject { |flag| flag == '-G' }
        config.build_settings['OTHER_CFLAGS'] = flags
      end

      # New architecture 비활성화
      config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] ||= []
      config.build_settings["GCC_PREPROCESSOR_DEFINITIONS"] << "RCT_NEW_ARCH_ENABLED=0"
    end
  end
end
