const { withDangerousMod } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Expo Config Plugin: BoringSSL-GRPC -G 플래그 에러 수정
 * EAS 빌드에서 자동 생성된 Podfile의 post_install 훅에 -G 플래그 제거 로직 추가
 */
module.exports = (config) => {
  console.log('\n========================================');
  console.log('🚀 [withPodfileFix] PLUGIN STARTING');
  console.log('========================================\n');
  
  return withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const podfilePath = path.join(projectRoot, 'ios', 'Podfile');
      
      console.log('🔧 [withPodfileFix] Fixing Podfile for BoringSSL-GRPC -G flag error...');
      console.log(`  📂 Project Root: ${projectRoot}`);
      console.log(`  📄 Podfile Path: ${podfilePath}`);
      
      if (fs.existsSync(podfilePath)) {
        console.log('✅ [withPodfileFix] Replacing entire Podfile with fixed version...');
        
        // 완전히 새로운 Podfile 내용 생성
        const newPodfileContent = `# ===============================================
# 🎯 PickPlay iOS Podfile (Expo SDK 54)
# ===============================================
# This Podfile is auto-generated by withPodfileFix.js
# 
# FIXES APPLIED:
# ✅ gRPC-Core/C++ forced to C++17 (fixes std::result_of)
# ✅ BoringSSL-GRPC -G flag removed
# ✅ Expo autolinking integrated (SDK 54)
# ✅ Firebase auto-managed by RNFB
# ✅ All pods optimized for Xcode 16
# ===============================================

platform :ios, '15.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'

# Expo modules autolinking (SDK 54)
# NOTE: expo-modules-autolinking removed from package.json to avoid conflicts
# Expo SDK will auto-install the correct version as a transitive dependency
begin
  require_relative '../node_modules/expo/scripts/autolinking'
  Pod::UI.puts '✅ Expo autolinking loaded from expo package'
rescue LoadError => e1
  begin
    require_relative '../node_modules/expo-modules-core/scripts/autolinking'
    Pod::UI.puts '✅ Expo autolinking loaded from expo-modules-core'
  rescue LoadError => e2
    Pod::UI.warn "⚠️  Expo autolinking not available:"
    Pod::UI.warn "   Path 1: ../node_modules/expo/scripts/autolinking (#{e1.message})"
    Pod::UI.warn "   Path 2: ../node_modules/expo-modules-core/scripts/autolinking (#{e2.message})"
    Pod::UI.warn "   Continuing without Expo autolinking - pods will be declared manually"
    
    # Stub to prevent crashes
    def use_expo_modules!(options = {})
      Pod::UI.warn '⚠️  use_expo_modules! stub - Expo modules not auto-linked'
    end
  end
end

# ✅ CRITICAL: Always define Expo::PostInstall stub
# CocoaPods expects this to exist, but Expo SDK may not define it
unless defined?(Expo::PostInstall)
  module Expo
    module PostInstall
      def self.install!(installer)
        Pod::UI.puts '✅ Expo::PostInstall stub - no additional config needed (Expo modules configured via use_expo_modules!)'
      end
    end
  end
end

use_frameworks! :linkage => :static

target 'PickPlay' do
  # React Native setup (FIRST - registers RN modules)
  use_react_native!(
    :path => '../node_modules/react-native',
    :hermes_enabled => true,
    :fabric_enabled => true,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  # Expo autolinking for native modules (AFTER RN setup)
  use_expo_modules!

  # ✅ CRITICAL: Explicitly declare Expo core modules
  # This ensures Expo modules are available even if autolinking fails
  pod 'ExpoModulesCore', :path => '../node_modules/expo-modules-core'
  pod 'Expo', :path => '../node_modules/expo'
  
  # ✅ CRITICAL: Firebase pods (required by RNFB)
  # Let CocoaPods resolve the version (no manual version pinning)
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Functions'
  
  # ✅ CRITICAL: Explicitly declare ALL React Native community modules
  # This prevents "Unable to find specification" errors for ExpoHead dependencies
  # Pod names MUST match the actual .podspec file names!
  
  # ✅ CRITICAL: React Native community modules + Codegen support
  # Must declare both the module AND its Codegen podspec for New Architecture
  
  # Screens (+ Codegen)
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  
  # Reanimated (+ Codegen)
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
  
  # Gesture Handler (+ Codegen)
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  
  # Safe Area Context (+ Codegen)
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  
  # Async Storage (+ Codegen)
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  
  # WebView (+ Codegen)
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  
  # Google Mobile Ads (+ Codegen)
  pod 'RNGoogleMobileAds', :path => '../node_modules/react-native-google-mobile-ads'
  
  # Worklets (+ Codegen)
  pod 'RNWorklets', :path => '../node_modules/react-native-worklets'
  
  # Old Architecture modules (no Codegen)
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
end

post_install do |installer|
  puts "🔧 [post_install] Custom Podfile post_install hook executing..."
  
  # ✅ CRITICAL FIX: BoringSSL-GRPC COMPILER_FLAGS 제거 (Stack Overflow 검증된 방법)
  puts "=" * 80
  puts "🔧 [post_install] CRITICAL FIX: Removing -GCC_WARN_INHIBIT_ALL_WARNINGS from BoringSSL-GRPC"
  puts "=" * 80
  
  modified_count = 0
  installer.pods_project.targets.each do |target|
    # BoringSSL-GRPC와 gRPC-Core 모두 처리
    if target.name == 'BoringSSL-GRPC' || target.name == 'gRPC-Core' || target.name == 'gRPC-C++'
      puts "🎯 Found target: #{target.name}"
      
      # Stack Overflow 검증된 방법: source_build_phase.files의 COMPILER_FLAGS 수정
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          original = file.settings['COMPILER_FLAGS']
          flags = original.split
          
          # BoringSSL-GRPC: -G 플래그 제거
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' || flag == '-G' }
          
          # gRPC-Core/C++: -std=c++20 제거 (CRITICAL!)
          if target.name == 'gRPC-Core' || target.name == 'gRPC-C++'
            flags.reject! { |flag| flag =~ /-std=c\+\+20/ }
          end
          
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
          
          if original != file.settings['COMPILER_FLAGS']
            modified_count += 1
          end
        end
      end
      
      # build_settings도 정화 (추가 방어)
      target.build_configurations.each do |config|
        ['WARNING_CFLAGS', 'OTHER_CFLAGS', 'OTHER_CPLUSPLUSFLAGS'].each do |setting|
          if config.build_settings[setting]
            original = config.build_settings[setting].to_s
            cleaned = original.gsub('-GCC_WARN_INHIBIT_ALL_WARNINGS', '').gsub(/\s*-G\s+/, ' ').strip
            
            # gRPC: -std=c++20 제거 (CRITICAL!)
            if (target.name == 'gRPC-Core' || target.name == 'gRPC-C++') && setting == 'OTHER_CPLUSPLUSFLAGS'
              cleaned = cleaned.gsub(/-std=c\+\+20/, '').strip
            end
            
            if original != cleaned
              config.build_settings[setting] = cleaned
              modified_count += 1
            end
          end
        end
        
        # ⚠️ CRITICAL: gRPC C++17 강제 (std::result_of는 C++20에서 제거됨)
        if target.name == 'gRPC-Core' || target.name == 'gRPC-C++'
          puts "  🔧 FORCING C++17 for #{target.name}/#{config.name}"
          
          # Method 1: build_settings로 설정
          config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
          config.build_settings['GCC_C_LANGUAGE_STANDARD'] = 'c17'
          
          # Method 2: OTHER_CPLUSPLUSFLAGS에 직접 -std=c++17 추가 (CRITICAL!)
          # Xcode가 response file 생성 시 이 플래그를 사용함
          cxxflags = config.build_settings['OTHER_CPLUSPLUSFLAGS'] || '$(inherited)'
          cxxflags = cxxflags.is_a?(Array) ? cxxflags.join(' ') : cxxflags.to_s
          
          # 모든 -std=c++XX 플래그 제거 (c++20 포함)
          cxxflags = cxxflags.gsub(/-std=c\+\+\d+/, '').strip
          # -std=c++17만 추가 + template warning 억제
          cxxflags = "#{cxxflags} -std=c++17 -Wno-missing-template-arg-list-after-template-kw".strip
          
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = cxxflags
          
          # WARNING_CFLAGS 수정 - 여러 warning 억제
          warning_flags = config.build_settings['WARNING_CFLAGS'] || '$(inherited)'
          warning_flags = warning_flags.is_a?(Array) ? warning_flags.join(' ') : warning_flags.to_s
          
          # 빌드를 막을 수 있는 warning들 억제
          suppressed_warnings = [
            '-Wno-missing-template-arg-list-after-template-kw',  # gRPC template 이슈
            '-Wno-shorten-64-to-32',                             # gRPC/BoringSSL 일반적 warning
            '-Wno-comma',                                        # gRPC warning
            '-Wno-unreachable-code'                              # gRPC warning
          ]
          
          suppressed_warnings.each do |flag|
            warning_flags = warning_flags.gsub(flag, '').strip  # 중복 제거
          end
          
          warning_flags = "#{warning_flags} #{suppressed_warnings.join(' ')}".strip
          config.build_settings['WARNING_CFLAGS'] = warning_flags
          
          # Deployment target 수정 (Xcode 16 호환성)
          deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
          if deployment_target && deployment_target.to_f < 12.0
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
            puts "     └─ Updated IPHONEOS_DEPLOYMENT_TARGET: #{deployment_target} -> 12.0"
          end
          
          puts "     └─ Removed all -std=c++XX flags"
          puts "     └─ CLANG_CXX_LANGUAGE_STANDARD = c++17"
          puts "     └─ OTHER_CPLUSPLUSFLAGS = #{cxxflags}"
          puts "     └─ WARNING_CFLAGS with #{suppressed_warnings.length} suppressions"
          
          modified_count += 1
        end
      end
      
      puts "  ✅ Modified #{target.name} (#{modified_count} flags)"
    end
  end
  
  if modified_count == 0
    puts "  ⚠️  WARNING: No flags were modified!"
  end
  
  puts "=" * 80
  
  # ✅ CRITICAL: Link Codegen podspecs for New Architecture modules
  puts "=" * 80
  puts "🔧 [post_install] Linking Codegen podspecs for New Architecture..."
  puts "=" * 80
  
  codegen_dir = File.join(Dir.pwd, '..', 'ios', 'build', 'generated', 'ios')
  if Dir.exist?(codegen_dir)
    puts "  📂 Codegen dir: #{codegen_dir}"
    
    # Ensure ReactCodegen podspec is in the project
    installer.pods_project.targets.each do |target|
      if target.name == 'ReactCodegen'
        puts "  ✅ ReactCodegen target found - Codegen will be linked"
      end
    end
  else
    puts "  ⚠️  Codegen directory not found (may be generated during build)"
  end
  
  puts "=" * 80
  
  # React Native post install tweaks
  react_native_post_install(installer)
  
  # 🔧 추가 방어: 모든 Pod 타겟의 deployment target 수정 (Xcode 16 호환성)
  puts "=" * 80
  puts "🔧 [post_install] Fixing deployment targets for Xcode 16..."
  puts "=" * 80
  
  deployment_fix_count = 0
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
      if deployment_target && deployment_target.to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
        deployment_fix_count += 1
        puts "  📱 #{target.name}: #{deployment_target} -> 12.0"
      end
      
      # 🛡️ PREVENTION: Swift 5 compatibility for all pods
      config.build_settings['SWIFT_VERSION'] ||= '5.0'
      
      # 🛡️ PREVENTION: Disable strict warning-as-error for stability
      if config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS']
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
      end
      
      # 🛡️ PREVENTION: Enable module stability for Swift
      if config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION']
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
  
  puts "  ✅ Fixed #{deployment_fix_count} deployment targets"
  puts "  ✅ Applied Swift 5 compatibility to all pods"
  puts "  ✅ Disabled treat-warnings-as-errors"
  puts "  ✅ Enabled module stability for Swift"
  puts "=" * 80

  # ✅ 추가 방어: xcconfig/pbxproj 백업 정화
  puts "=" * 80
  puts "🔧 [post_install] Applying BACKUP DEFENSE (xcconfig + pbxproj)..."
  puts "=" * 80
  puts "ℹ️  CWD: #{Dir.pwd}"
  
  # 🛡️ BACKUP 1: xcconfig 파일 정화 (Pass 1 - save 전)
  begin
    puts "🛡️  [Backup 1/3] Cleaning xcconfig files (before save)..."
    
    xcconfig_count = 0
    target_support = File.join(Dir.pwd, 'Pods', 'Target Support Files')
    
    puts "  📂 Target Support path: #{target_support}"
    puts "  📂 Exists: #{Dir.exist?(target_support)}"
    
    if Dir.exist?(target_support)
      # 먼저 모든 xcconfig 파일 찾기 - glob 패턴을 문자열로 직접 생성
      glob_pattern = "#{target_support}/*/*.xcconfig"
      all_xcconfigs = Dir.glob(glob_pattern)
      puts "  📝 Glob pattern: #{glob_pattern}"
      puts "  📝 Found #{all_xcconfigs.length} total xcconfig files"
      
      all_xcconfigs.each do |file|
        if file.include?('BoringSSL') || file.include?('gRPC')
          content = File.read(file)
          original = content.dup
          
          content.gsub!('-GCC_WARN_INHIBIT_ALL_WARNINGS', '')
          content.gsub!(/\s*-G\s+/, ' ')
          
          # gRPC C++17 강제 (xcconfig 레벨에서도) - CRITICAL FIX
          if file.include?('gRPC-Core') || file.include?('gRPC-C++')
            # STEP 1: -std=c++20 완전 제거 (CRITICAL!)
            content.gsub!(/-std=c\+\+20/, '')
            content.gsub!(/'-std=c\+\+20'/, '')
          end
          
          if file.include?('gRPC-Core') || file.include?('gRPC-C++')
            # CLANG_CXX_LANGUAGE_STANDARD 처리
            if content.include?('CLANG_CXX_LANGUAGE_STANDARD')
              content.gsub!(/CLANG_CXX_LANGUAGE_STANDARD\\s*=\\s*c\\+\\+20/, 'CLANG_CXX_LANGUAGE_STANDARD = c++17')
              puts "  🔧 Changed C++20 -> C++17 in: #{File.basename(file)}"
            else
              content += "\\nCLANG_CXX_LANGUAGE_STANDARD = c++17\\n"
              puts "  🔧 Added CLANG_CXX_LANGUAGE_STANDARD to: #{File.basename(file)}"
            end
            
            # OTHER_CPLUSPLUSFLAGS 처리 (CRITICAL!)
            if content.include?('OTHER_CPLUSPLUSFLAGS')
              # 기존 라인을 찾아서 -std=c++17 + warning 억제 추가
              content.gsub!(/(OTHER_CPLUSPLUSFLAGS\\s*=.*)$/) do |match|
                line = $1
                # -std=c++XX 제거하고 -std=c++17 추가
                line = line.gsub(/-std=c\\+\\+\\d+/, '').strip
                # template warning 억제도 추가
                line = line.gsub(/-Wno-missing-template-arg-list-after-template-kw/, '').strip
                "#{line} -std=c++17 -Wno-missing-template-arg-list-after-template-kw"
              end
              puts "  🔧 Modified OTHER_CPLUSPLUSFLAGS in: #{File.basename(file)}"
            else
              # OTHER_CPLUSPLUSFLAGS가 없으면 새로 추가
              content += "OTHER_CPLUSPLUSFLAGS = $(inherited) -std=c++17 -Wno-missing-template-arg-list-after-template-kw\\n"
              puts "  🔧 Added OTHER_CPLUSPLUSFLAGS to: #{File.basename(file)}"
            end
          end
          
          if content != original
            File.write(file, content)
            xcconfig_count += 1
            puts "  🧹 Cleaned: #{File.basename(File.dirname(file))}/#{File.basename(file)}"
          end
        end
      end
    else
      puts "  ❌ Target Support Files directory not found!"
    end
    
    puts "  ✅ Backup 1 complete (#{xcconfig_count} files cleaned)"
    
  rescue => e
    puts "❌ [Backup 1] ERROR: #{e.message}"
    puts "     #{e.backtrace.first}"
  end
  
  # 🛡️ BACKUP 2: pbxproj 정화
  begin
    puts "🛡️  [Backup 2/3] Cleaning project.pbxproj..."
    
    project_file = File.join(Dir.pwd, 'Pods', 'Pods.xcodeproj', 'project.pbxproj')
    
    if File.exist?(project_file)
      pbxproj = File.read(project_file)
      original = pbxproj.dup
      
      pbxproj.gsub!('-GCC_WARN_INHIBIT_ALL_WARNINGS', '')
      pbxproj.gsub!(/\s*-G\s+/, ' ')
      
      if pbxproj != original
        File.write(project_file, pbxproj)
        puts "  🧹 Cleaned project.pbxproj"
      else
        puts "  ℹ️  No changes needed in pbxproj"
      end
    else
      puts "  ❌ project.pbxproj not found at: #{project_file}"
    end
    
    puts "  ✅ Backup 2 complete"
    
  rescue => e
    puts "❌ [Backup 2] ERROR: #{e.message}"
    puts "     #{e.backtrace.first}"
  end
  
  # 💾 저장
  puts "💾 Saving Pods project..."
  installer.pods_project.save
  puts "✅ Pods project saved"
  
  # 🛡️ BACKUP 3: xcconfig 재정화 (Pass 2 - save 후, 최종 방어선)
  begin
    puts "🛡️  [Backup 3/3] Re-cleaning xcconfig files (after save)..."
    
    xcconfig_count = 0
    target_support = File.join(Dir.pwd, 'Pods', 'Target Support Files')
    
    if Dir.exist?(target_support)
      glob_pattern = "#{target_support}/*/*.xcconfig"
      all_xcconfigs = Dir.glob(glob_pattern)
      
      all_xcconfigs.each do |file|
        if file.include?('BoringSSL') || file.include?('gRPC')
          content = File.read(file)
          modified = false
          
          if content.include?('-GCC_WARN_INHIBIT_ALL_WARNINGS') || content =~ /\s-G\s/
            content.gsub!('-GCC_WARN_INHIBIT_ALL_WARNINGS', '')
            content.gsub!(/\s*-G\s+/, ' ')
            modified = true
          end
          
          # gRPC C++17 재확인 (Pass 2에서도) - CRITICAL FIX
          if (file.include?('gRPC-Core') || file.include?('gRPC-C++'))
            # STEP 1: -std=c++20 완전 제거 (save 후에도!)
            if content.include?('-std=c++20') || content.include?("'-std=c++20'")
              content.gsub!(/-std=c\+\+20/, '')
              content.gsub!(/'-std=c\+\+20'/, '')
              modified = true
              puts "  🗑️  Removed -std=c++20 from: #{File.basename(file)}"
            end
          end
          
          if (file.include?('gRPC-Core') || file.include?('gRPC-C++'))
            # CLANG_CXX_LANGUAGE_STANDARD 재확인
            if content =~ /CLANG_CXX_LANGUAGE_STANDARD\\s*=\\s*c\\+\\+20/
              content.gsub!(/CLANG_CXX_LANGUAGE_STANDARD\\s*=\\s*c\\+\\+20/, 'CLANG_CXX_LANGUAGE_STANDARD = c++17')
              modified = true
              puts "  🔧 Fixed C++20 -> C++17 in: #{File.basename(file)}"
            elsif !content.include?('CLANG_CXX_LANGUAGE_STANDARD')
              content += "\\nCLANG_CXX_LANGUAGE_STANDARD = c++17\\n"
              modified = true
              puts "  🔧 Added CLANG_CXX_LANGUAGE_STANDARD to: #{File.basename(file)}"
            end
            
            # OTHER_CPLUSPLUSFLAGS 재확인 (CRITICAL!)
            if content.include?('OTHER_CPLUSPLUSFLAGS')
              original_flags = content.dup
              content.gsub!(/(OTHER_CPLUSPLUSFLAGS\\s*=.*)$/) do |match|
                line = $1
                unless line.include?('-std=c++17') && line.include?('-Wno-missing-template-arg-list-after-template-kw')
                  line = line.gsub(/-std=c\\+\\+\\d+/, '').strip
                  line = line.gsub(/-Wno-missing-template-arg-list-after-template-kw/, '').strip
                  line = "#{line} -std=c++17 -Wno-missing-template-arg-list-after-template-kw"
                end
                line
              end
              if original_flags != content
                modified = true
                puts "  🔧 Fixed OTHER_CPLUSPLUSFLAGS in: #{File.basename(file)}"
              end
            else
              content += "OTHER_CPLUSPLUSFLAGS = $(inherited) -std=c++17 -Wno-missing-template-arg-list-after-template-kw\\n"
              modified = true
              puts "  🔧 Added OTHER_CPLUSPLUSFLAGS to: #{File.basename(file)}"
            end
          end
          
          if modified
            File.write(file, content)
            xcconfig_count += 1
            puts "  🔒 Re-cleaned: #{File.basename(File.dirname(file))}/#{File.basename(file)}"
          end
        end
      end
    end
    
    puts "  ✅ Backup 3 complete (#{xcconfig_count} files re-cleaned)"
    
  rescue => e
    puts "❌ [Backup 3] ERROR: #{e.message}"
    puts "     #{e.backtrace.first}"
  end
  
  puts ""
  puts "=" * 80
  puts "🎉 ALL FIXES & PREVENTIONS COMPLETED"
  puts "=" * 80
  puts ""
  puts "📋 APPLIED FIXES:"
  puts "  ✅ BoringSSL-GRPC: -G flag removed (#{modified_count} files)"
  puts "  ✅ gRPC-Core/C++: Forced to C++17 (std::result_of fix)"
  puts "  ✅ Deployment targets: #{deployment_fix_count} pods updated to iOS 12.0"
  puts "  ✅ xcconfig files: #{xcconfig_count} files cleaned (3 passes)"
  puts ""
  puts "🛡️  PREVENTIONS APPLIED:"
  puts "  ✅ Swift 5 compatibility enforced"
  puts "  ✅ Warning-as-error disabled"
  puts "  ✅ Module stability enabled"
  puts "  ✅ Firebase auto-managed by RNFB"
  puts ""
  puts "🔧 POST-INSTALL HOOKS:"
  puts "  ✅ react_native_post_install completed"
  puts "  ℹ️  Expo::PostInstall skipped (not required - Expo modules configured via use_expo_modules!)"
  
  puts ""
  puts "=" * 80
  puts "🚀 Podfile post_install completed successfully!"
  puts "=" * 80
end`;
        
        // 새로운 Podfile 저장
        fs.writeFileSync(podfilePath, newPodfileContent);
        console.log('✅ [withPodfileFix] Podfile replaced with VERIFIED SOLUTION (Stack Overflow + GitHub)');
        
        // 검증
        const updatedContent = fs.readFileSync(podfilePath, 'utf8');
        const hasBoringSSLLogic = updatedContent.includes('BoringSSL') && updatedContent.includes('GCC_WARN_INHIBIT_ALL_WARNINGS');
        if (hasBoringSSLLogic) {
          console.log('✅ [withPodfileFix] -GCC_WARN_INHIBIT_ALL_WARNINGS fix logic VERIFIED in new Podfile');
        } else {
          console.warn('⚠️  [withPodfileFix] -GCC_WARN_INHIBIT_ALL_WARNINGS fix logic NOT FOUND in new Podfile!');
        }
      } else {
        console.error('❌ [withPodfileFix] Podfile not found at', podfilePath);
        throw new Error(`Podfile not found: ${podfilePath}`);
      }
      
      console.log('\n========================================');
      console.log('✅ [withPodfileFix] PLUGIN COMPLETED');
      console.log('========================================\n');
      
      return config;
    },
  ]);
};
